In [1]:
def countdog(str):
    count = 0
    for word in str.lower().split():
        if word == 'dog':
            count += 1
    return count
    
#COUNT HELPS YOU MOVE THROUGH EAACH WORD OF THE STRING

In [2]:
countdog('this Dog runs faster than the other dog')

2

In [3]:
seq = ['soup','dog','salad','cat','goat']
list(filter(lambda word : word[0] == 's', seq))

['soup', 'salad']

In [7]:
seq

['soup', 'dog', 'salad', 'cat', 'goat']

In [10]:
import numpy as np

In [12]:
arr_2d = np.arange(50)

In [13]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
arr_2d.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])